npi = {"FC": {"name": "First Case", 
              "color": ""},
       "E": {"name": "State Emergency",
             "color": ""},
       "MDD": {"name": "Major Disaster Declaration",
               "color": ""},
       "NG": {"name": "National Guard Activation",
              "color": ""},
       "SC": {"name": "School Closure",
              "color": ""},
       "RB": {"name": "Restaurant and Bar Closure",
              "color": ""},
       "NEB": {"name": "Non-Essential Business Closure",
               "color": ""},
       "C": {"name": "Curfew",
             "color": ""},
       "SI": {"name": "Stay at Home",
              "color": ""},
       "W1135": {"name": "1135 Waiver Approved",
                 "color": ""},
       "G-10": {"name": "Gatherings limited to 10",
                "color": ""},
       "G-25": {"name": "Gatherings limited to 25",
                "color": ""},
       "G-50": {"name": "Gatherings limited to 50",
                "color": ""}, 
       "G-100": {"name": "Gatherings limited to 100",
                 "color": ""},
       "G-250": {"name": "Gatherings limited to 250",
                 "color": ""},
       "G-1000": {"name": "Gatherings limited to 1000",
                  "color": ""},
       "CS": {"name": "Community Spread",
              "color": ""}, 
       "T": {"name": "Testing",
             "color": ""}, 
       "SD": {"name": "Social Distancing",
              "color": ""}, 
       "ML": {"name": "Medical Licensure Relaxed",
              "color": ""},
       "ES": {"name": "Elective Surgeries Postpone",
              "color": ""}
      }

state_list = ['Alabama',
          'Alaska',
          'Arizona',
          'Arkansas',
          'California',
          'Colorado',
          'Connecticut',
          'Delaware',
          'District of Columbia',
          'Florida',
          'Georgia',
          'Hawaii', 
          'Idaho',
          'Illinois',
          'Indiana',
          'Iowa',
          'Kansas',
          'Kentucky',
          'Louisiana',
          'Maine',
          'Maryland',
          'Massachusetts',
          'Michigan',
          'Minnesota',
          'Mississippi',
          'Missouri',
          'Montana',
          'Nebraska',
          'Nevada',
          'New Hampshire',
          'New Jersey',
          'New Mexico',
          'New York',
          'North Carolina',
          'North Dakota',
          'Ohio',
          'Oklahoma',
          'Oregon',
          'Pennsylvania',
          'Puerto Rico',
          'Rhode Island',
          'South Carolina',
          'South Dakota',
          'Tennessee',
          'Texas',
          'Utah',
          'Vermont',
          'Virginia',
          'Washington',
          'West Virginia',
          'Wisconsin',
          'Wyoming']

us_state_abbrev = {
     'AL': 'Alabama',
     'AK': 'Alaska',
     'AS': 'American Samoa',
     'AZ': 'Arizona',
     'AR': 'Arkansas',
     'CA': 'California',
     'CO': 'Colorado',
     'CT': 'Connecticut',
     'DE': 'Delaware',
     'DC': 'District of Columbia',
     'FL': 'Florida',
     'GA': 'Georgia',
     'GU': 'Guam',
     'HI': 'Hawaii',
     'ID': 'Idaho',
     'IL': 'Illinois',
     'IN': 'Indiana',
     'IA': 'Iowa',
     'KS': 'Kansas',
     'KY': 'Kentucky',
     'LA': 'Louisiana',
     'ME': 'Maine',
     'MD': 'Maryland',
     'MA': 'Massachusetts',
     'MI': 'Michigan',
     'MN': 'Minnesota',
     'MS': 'Mississippi',
     'MO': 'Missouri',
     'MT': 'Montana',
     'NE': 'Nebraska',
     'NV': 'Nevada',
     'NH': 'New Hampshire',
     'NJ': 'New Jersey',
     'NM': 'New Mexico',
     'NY': 'New York',
     'NC': 'North Carolina',
     'ND': 'North Dakota',
     'MP': 'Northern Mariana Islands',
     'OH': 'Ohio',
     'OK': 'Oklahoma',
     'OR': 'Oregon',
     'PA': 'Pennsylvania',
     'PR': 'Puerto Rico',
     'RI': 'Rhode Island',
     'SC': 'South Carolina',
     'SD': 'South Dakota',
     'TN': 'Tennessee',
     'TX': 'Texas',
     'UT': 'Utah',
     'VT': 'Vermont',
     'VI': 'Virgin Islands',
     'VA': 'Virginia',
     'WA': 'Washington',
     'WV': 'West Virginia',
     'WI': 'Wisconsin',
     'WY': 'Wyoming'
}


npi_weights = {"G-1000": 5,
               "G-250": 6,
               "G-100": 7,
               "G-50": 8,
               "G-25": 9,
               "G-10": 10,
               "RB": 15,
               "NEB": 15,
               "SC": 15,
               "SI": 20,
               "C": 16,
               "E": 10,
               "NG": 10,
               "MDD": 10
              }